services:
  - type: web
    name: engawa
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    autoDeploy: true
